### PR TITLE
Made it on a more efficient way. Now complexity is N instead of 2N

### PR DESCRIPTION
**Pull request by salvacorts**
make it on a array instead of on a recursive way

### CODE REVIEW

**Comment by yamanetoshi** [comment]
Thx! Informative!

**Comment by yamanetoshi** [comment]
I thought carefully, but I think that the previous implementation is also O(n)?

**Comment by salvacorts** [comment]
Yes, its is, im sorry. but it is 2n with is twice lower than the array approach. 
So its still a better approach

**Comment by salvacorts** [comment]
http://fusharblog.com/solving-linear-recurrence-for-programming-contest/ It is worth reading

**Comment by yamanetoshi** [comment]
Thank you for introducing a good pointer.
The interesting thing is, when the argument is a large value, which implementation is more efficient.

**Comment by salvacorts** [comment]
Array of course. it will be much faster and will use half memory

**Pull request merged**
